package pubSubBuilderFinal.gui.pub;

import java.awt.GridBagConstraints;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import pubSubBuilderFinal.data.Data;
import pubSubBuilderFinal.gui.Result;
import pubSubBuilderFinal.gui.WelcomePage;
import pubSubBuilderFinal.publisher.types.HeartbeatPublisher;
import pubSubBuilderFinal.publisher.types.HumidityPublisher;
import pubSubBuilderFinal.publisher.types.PowerPublisher;
import pubSubBuilderFinal.publisher.types.Publisher;
import pubSubBuilderFinal.publisher.types.TemperaturePublisher;
import pubSubBuilderFinal.publisher.types.TimePublisher;
import pubSubBuilderFinal.publisher.types.WindPublisher;

/**
 *
 * @author Yash Divecha
 */
public class Device2PubConfig extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

	private Data myData = null;
	private Result result;

	private ArrayList<javax.swing.JCheckBox> topicCheckBox; // GUI dynamic
															// checkboxes
	private ArrayList<String> topicsPubSelected;
	private ArrayList<Publisher> publisherSelected;

	/**
	 * Creates new form Device2Config
	 */
	public Device2PubConfig(Data myDataIn, Result resultIn) {
		this.myData = myDataIn;
		this.result = resultIn;
		initComponents();
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		// setLayout(new java.awt.FlowLayout());
		setLayout(new java.awt.GridBagLayout());
		createCheckbox();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("What Topics you want to Publish?");

		jButton1.setText("Back");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Configure");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(86, 86, 86).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(74, Short.MAX_VALUE)
								.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(66, 66, 66).addComponent(jButton2).addGap(291, 291, 291)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(44, 44, 44).addComponent(jLabel1).addGap(317, 317, 317)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton2))
						.addGap(47, 47, 47)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		this.setVisible(false);
		new WelcomePage(myData, result).setVisible(true);
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		topicsPubSelected = new ArrayList<>();
		publisherSelected = new ArrayList<>();

		// This is used to get selected checkbox and add to the database and
		// create new publuishers as per checkbox topic
		int index = 0;
		for (int i = 0; i < topicCheckBox.size(); i++) {
			if (topicCheckBox.get(i).isSelected()) {
				topicsPubSelected.add(topicCheckBox.get(i).getText());
				Publisher pub;

				if (topicsPubSelected.get(index).contains("/Time")) {
					pub = new TimePublisher(topicsPubSelected.get(index));
					pub.setName("Device 2");
					publisherSelected.add(pub);
				}
				if (topicsPubSelected.get(index).contains("/Humidity")) {
					pub = new HumidityPublisher(topicsPubSelected.get(index));
					pub.setName("Device 2");
					publisherSelected.add(pub);
				}
				if (topicsPubSelected.get(index).contains("/Wind")) {
					pub = new WindPublisher(topicsPubSelected.get(index));
					pub.setName("Device 2");
					publisherSelected.add(pub);
				}
				if (topicsPubSelected.get(index).contains("/Temperature")) {
					pub = new TemperaturePublisher(topicsPubSelected.get(index));
					pub.setName("Device 2");
					publisherSelected.add(pub);
				}
				if (topicsPubSelected.get(index).contains("/Heartbeat")) {
					pub = new HeartbeatPublisher(topicsPubSelected.get(index));
					pub.setName("Device 2");
					publisherSelected.add(pub);
				}
				if (topicsPubSelected.get(index).contains("/Power")) {
					pub = new PowerPublisher(topicsPubSelected.get(index));
					pub.setName("Device 2");
					publisherSelected.add(pub);
				}
				System.out.println(publisherSelected.get(index).getName());
				index++;
			}
		}
		result.setDevice2PublishersSelected(publisherSelected);
		result.setDevice2SelectedTopics(topicsPubSelected);
		result.setDevice2PubConfigured(true);
		JOptionPane.showMessageDialog(null, "Device 2 Publisher Successfully Configured: ", "MESSAGE",
				JOptionPane.INFORMATION_MESSAGE);

	}// GEN-LAST:event_jButton2ActionPerformed

	private void createCheckbox() {

		topicCheckBox = new ArrayList<>();

		ArrayList<String> device2Topics = myData.getDevice2Data();

		GridBagConstraints gc = new GridBagConstraints();
		gc.weightx = 10;
		gc.weighty = 0.5;

		gc.anchor = GridBagConstraints.LINE_START;
		gc.gridx = 1;
		gc.gridy = 0;
		getContentPane().add(jLabel1, gc);
		int i = 0;
		for (i = 0; i < device2Topics.size(); i++) {
			javax.swing.JCheckBox box = new javax.swing.JCheckBox(device2Topics.get(i));
			topicCheckBox.add(i, box);

			gc.anchor = GridBagConstraints.LINE_START;
			gc.gridx = 1;
			gc.gridy = i + 1;
			getContentPane().add(box, gc);

		}

		gc.weighty = 10;
		gc.gridx = 1;
		gc.gridy = i + 1;
		getContentPane().add(jButton1, gc);

		// gc.weighty = 10;
		gc.gridx = 2;
		gc.gridy = i + 1;
		getContentPane().add(jButton2, gc);
		// pack();
	}

}
